<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="43456" started-at="2018-02-20T03:46:11Z" finished-at="2018-02-20T03:46:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="43456" started-at="2018-02-20T03:46:11Z" finished-at="2018-02-20T03:46:55Z">
      <class name="datadriven.Wordpresslogin">
        <test-method status="PASS" signature="browser()[pri:0, instance:datadriven.Wordpresslogin@464bee09]" name="browser" is-config="true" duration-ms="7125" started-at="2018-02-19T22:46:11Z" finished-at="2018-02-19T22:46:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser -->
        <test-method status="FAIL" signature="logintoword(java.lang.String, java.lang.String)[pri:0, instance:datadriven.Wordpresslogin@464bee09]" name="logintoword" duration-ms="859" started-at="2018-02-19T22:46:19Z" data-provider="testdata" finished-at="2018-02-19T22:46:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[adminnn]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at datadriven.Wordpresslogin.logintoword(Wordpresslogin.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintoword -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:datadriven.Wordpresslogin@464bee09]" name="teardown" is-config="true" duration-ms="4452" started-at="2018-02-19T22:46:19Z" finished-at="2018-02-19T22:46:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="browser()[pri:0, instance:datadriven.Wordpresslogin@464bee09]" name="browser" is-config="true" duration-ms="6328" started-at="2018-02-19T22:46:24Z" finished-at="2018-02-19T22:46:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser -->
        <test-method status="PASS" signature="logintoword(java.lang.String, java.lang.String)[pri:0, instance:datadriven.Wordpresslogin@464bee09]" name="logintoword" duration-ms="8239" started-at="2018-02-19T22:46:30Z" data-provider="testdata" finished-at="2018-02-19T22:46:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintoword -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:datadriven.Wordpresslogin@464bee09]" name="teardown" is-config="true" duration-ms="4043" started-at="2018-02-19T22:46:38Z" finished-at="2018-02-19T22:46:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="browser()[pri:0, instance:datadriven.Wordpresslogin@464bee09]" name="browser" is-config="true" duration-ms="7335" started-at="2018-02-19T22:46:42Z" finished-at="2018-02-19T22:46:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser -->
        <test-method status="FAIL" signature="logintoword(java.lang.String, java.lang.String)[pri:0, instance:datadriven.Wordpresslogin@464bee09]" name="logintoword" duration-ms="935" started-at="2018-02-19T22:46:50Z" data-provider="testdata" finished-at="2018-02-19T22:46:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[adminnn]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at datadriven.Wordpresslogin.logintoword(Wordpresslogin.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintoword -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:datadriven.Wordpresslogin@464bee09]" name="teardown" is-config="true" duration-ms="4092" started-at="2018-02-19T22:46:51Z" finished-at="2018-02-19T22:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- datadriven.Wordpresslogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
